apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_DATABASE: "three_tier_db"
  MYSQL_USER: "YOUR_DB_USER"
  MYSQL_PASSWORD: "YOUR_DB_PASSWORD"
  MYSQL_ROOT_PASSWORD: "YOUR_ROOT_PASSWORD"
